word1 = input("what is your sentence?: ")
word2 = input("what word do you want to replace?: ")
word3 = input(" what word do you want to replace the word with?: ")
new_word = word1.replace(word2,word3)
print(" your new word is " + new_word)